<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Contractor Applications Report</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 10px;
        }

        h1 {
            text-align: center;
            font-size: 16px;
            margin-bottom: 20px;
        }

        .filters {
            background: #f5f5f5;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #ddd;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #333;
            padding: 5px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
            font-weight: bold;
        }

        .badge {
            padding: 2px 5px;
            border-radius: 3px;
            font-size: 9px;
        }

        .badge-success {
            background: #28a745;
            color: white;
        }

        .badge-danger {
            background: #dc3545;
            color: white;
        }

        .badge-info {
            background: #17a2b8;
            color: white;
        }

        .badge-secondary {
            background: #6c757d;
            color: white;
        }

        .footer {
            margin-top: 20px;
            text-align: center;
            font-size: 9px;
            color: #666;
        }
    </style>
</head>

<body>
    <h1>Contractor Applications Report</h1>

    <div class="filters">
        <strong>Report Filters:</strong><br>
        @if(!empty($filters['status']))
            Status: {{ ucfirst(str_replace('_', ' ', $filters['status'])) }}<br>
        @endif
        @if(!empty($filters['date_from']))
            From: {{ $filters['date_from'] }}<br>
        @endif
        @if(!empty($filters['date_to']))
            To: {{ $filters['date_to'] }}<br>
        @endif
        @if(!empty($filters['search']))
            Search: {{ $filters['search'] }}<br>
        @endif
        Generated: {{ now()->format('Y-m-d H:i:s') }}<br>
        Total Records: {{ $applications->count() }}
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 12%">Certificate #</th>
                <th style="width: 20%">Applicant</th>
                <th style="width: 12%">Mobile</th>
                <th style="width: 15%">NID</th>
                <th style="width: 18%">Status</th>
                <th style="width: 13%">Entry By</th>
                <th style="width: 10%">Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($applications as $app)
                <tr>
                    <td>{{ $app->old_certificate_number }}</td>
                    <td>{{ $app->applicant_name_en }}</td>
                    <td>{{ $app->mobile_no }}</td>
                    <td>{{ $app->nid_number }}</td>
                    <td>{{ $app->status_label }}</td>
                    <td>{{ $app->entryBy?->full_name ?? 'N/A' }}</td>
                    <td>{{ $app->created_at->format('Y-m-d') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Legacy Permits Management System
    </div>
</body>

</html>